// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDeWbsG-4VsmKSpdmXPDi0FFyeIpS6_4',
    appId: '1:236105794668:web:1a1419561566b6efe3c449',
    messagingSenderId: '236105794668',
    projectId: 'interntask-b7de5',
    authDomain: 'interntask-b7de5.firebaseapp.com',
    storageBucket: 'interntask-b7de5.firebasestorage.app',
    measurementId: 'G-4G4Z6D3CL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Voib6vsPOdaGkwgEgW1biPLVGt542LI',
    appId: '1:236105794668:android:e393b161156d40aae3c449',
    messagingSenderId: '236105794668',
    projectId: 'interntask-b7de5',
    storageBucket: 'interntask-b7de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0VyL3npCSFS787kV06uckPtV0BblBdGc',
    appId: '1:236105794668:ios:9d242860353fde06e3c449',
    messagingSenderId: '236105794668',
    projectId: 'interntask-b7de5',
    storageBucket: 'interntask-b7de5.firebasestorage.app',
    iosBundleId: 'com.example.interntask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0VyL3npCSFS787kV06uckPtV0BblBdGc',
    appId: '1:236105794668:ios:9d242860353fde06e3c449',
    messagingSenderId: '236105794668',
    projectId: 'interntask-b7de5',
    storageBucket: 'interntask-b7de5.firebasestorage.app',
    iosBundleId: 'com.example.interntask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVDeWbsG-4VsmKSpdmXPDi0FFyeIpS6_4',
    appId: '1:236105794668:web:e971c5b6700b2ef7e3c449',
    messagingSenderId: '236105794668',
    projectId: 'interntask-b7de5',
    authDomain: 'interntask-b7de5.firebaseapp.com',
    storageBucket: 'interntask-b7de5.firebasestorage.app',
    measurementId: 'G-02B39Q0P0J',
  );
}
